In [2]:
import pandas as pd

df = pd.read_csv("../data/processed/repositories.csv")

In [3]:
df.head(1)

,Repository Name,Description,Topics,Domain,Primary Language,Stars Count,Forks Count,Updated At,combined_text
0,tensorflow,An Open Source Machine Learning Framework for ...,"deep-learning, deep-neural-networks, distribut...",Machine Learning,C++,194622,75263,2026-04-10T10:08:00Z,an open source machine learning framework for ...

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=10000,
    ngram_range=(1,2)
)

X = vectorizer.fit_transform(df['combined_text'])

In [5]:
X.shape

(4997, 10000)

In [6]:
vectorizer.get_feature_names_out()[:50]

array(['10', '100', '100 days', '1000', '10000', '10000 gpus', '10x',
       '10x faster', '11', '12', '12 weeks', '150', '16k', '180', '1x',
       '1x 2x', '20', '2017', '2018', '2020', '2021', '2022', '2022 ai',
       '2023', '2024', '2025', '2026', '2026 codinginterviewquestions',
       '20版入门实例代码', '20版入门实例代码 实战教程', '21', '229', '229 machine', '24',
       '24 lessons', '25', '2d', '2d 3d', '2d game', '2dgame',
       '2dgameengine', '2fa', '2fa android', '2nd', '2nd edition', '2wd',
       '2wd 4wd', '2x', '2x android', '30'], dtype=object)

In [7]:
X[0].toarray()

array([[0., 0., 0., ..., 0., 0., 0.]], shape=(1, 10000))

In [11]:
from sklearn.metrics.pairwise import cosine_similarity

In [12]:
similarities = cosine_similarity(X[0], X)

In [13]:
similarities.shape

(1, 4997)

In [16]:
similarities[0][:10]

array([1.        , 0.10900638, 0.08756374, 0.11446397, 0.06548063,
       0.19815512, 0.06281463, 0.07090665, 0.10386749, 0.09608072])

In [17]:
similarity_score = list(enumerate(similarities[0]))

In [18]:
similarity_score = sorted(
    similarity_score,
    key=lambda x: x[1],
    reverse=True
)

In [19]:
similarity_score[:10]

[(0, np.float64(1.0)),
 (997, np.float64(0.9544143643631111)),
 (200, np.float64(0.9165943249802607)),
 (67, np.float64(0.4035373842019475)),
 (90, np.float64(0.3933286138566248)),
 (130, np.float64(0.3097412975256691)),
 (279, np.float64(0.3090256988519475)),
 (3832, np.float64(0.2907892935512763)),
 (259, np.float64(0.28874818320754075)),
 (112, np.float64(0.2848174145409226))]

In [21]:
indices = [i[0] for i in similarity_score[1:11]]

df.iloc[indices][["Repository Name", "Description", "Primary Language", "Stars Count"]]

,Repository Name,Description,Primary Language,Stars Count
997,tensorflow,An Open Source Machine Learning Framework for ...,C++,194622
200,tensorflow,An Open Source Machine Learning Framework for ...,C++,194622
67,handson-ml,⛔️ DEPRECATED – See https://github.com/ageron/...,Jupyter Notebook,25747
90,onnx,Open standard for machine learning interoperab...,Python,20630
130,kubeflow,Machine Learning Toolkit for Kubernetes,0,15565
279,onnx,Open standard for machine learning interoperab...,Python,20630
3832,onnx,Open standard for machine learning interoperab...,Python,20630
259,handson-ml,⛔️ DEPRECATED – See https://github.com/ageron/...,Jupyter Notebook,25747
112,CNTK,"Microsoft Cognitive Toolkit (CNTK), an open so...",C++,17603
64,awesome-deep-learning-papers,The most cited deep learning papers,TeX,26106

In [47]:
# Recommendation Function

def recommend(repo_name, n=2):
    repo_indices = df.index[df["Repository Name"] == repo_name].tolist()

    if not repo_indices:
        return "Repository not found"

    idx = repo_indices[0]

    repo_vector = X[idx]

    similarities = cosine_similarity(repo_vector, X)[0] # 1-d array

    similarity_scores = list(enumerate(similarities))

    similarity_scores = sorted(
        similarity_scores,
        key=lambda x:x[1],
        reverse=True
    )

    similarity_scores = similarity_scores[1:n+1]

    indices = [i[0] for i in similarity_scores]

    recommendations = df.iloc[indices]

    return recommendations

In [48]:
recommend('pandas')

,Repository Name,Description,Topics,Domain,Primary Language,Stars Count,Forks Count,Updated At,combined_text
1602,pandas,Flexible and powerful data analysis / manipula...,"alignment, data-analysis, data-science, flexib...",Data Science,Python,48453,19872,2026-04-10T08:07:39Z,flexible and powerful data analysis manipulati...
417,DeepSeek-V3,0,0,Python,Python,102543,16629,2026-04-10T09:43:01Z,0 0 python python