In [22]:
import pandas as pd 
import numpy as np

In [23]:
df= pd.read_csv("../data/github_top_repositories_V2.csv")

In [24]:
df.sample(2)

,Domain,Repository Name,Full Name,Description,Primary Language,Stars Count,Forks Count,Open Issues Count,Has Wiki,Has Pages,Has Projects,Size (KB),Created At,Updated At,Pushed At,Default Branch,Owner Login,Owner Type,License,Topics
3834,Artificial Intelligence,Ciphey,bee-san/Ciphey,⚡ Automatically decrypt encryptions without kn...,Rust,21303,1429,7,True,False,False,22317,2019-07-16T20:20:39Z,2026-04-10T09:02:45Z,2026-04-07T14:58:22Z,master,bee-san,User,MIT License,"artificial-intelligence, cipher, cpp, cryptogr..."
735,JavaScript,nodemon,remy/nodemon,Monitor for any changes in your node.js applic...,JavaScript,26696,1751,12,True,False,False,3016,2010-10-03T12:50:52Z,2026-04-10T06:49:09Z,2026-04-04T22:54:15Z,main,remy,User,MIT License,"node, nodemon, watch"

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Domain             5000 non-null   object
 1   Repository Name    5000 non-null   object
 2   Full Name          5000 non-null   object
 3   Description        5000 non-null   object
 4   Primary Language   5000 non-null   object
 5   Stars Count        5000 non-null   int64
 6   Forks Count        5000 non-null   int64
 7   Open Issues Count  5000 non-null   int64
 8   Has Wiki           5000 non-null   bool
 9   Has Pages          5000 non-null   bool
 10  Has Projects       5000 non-null   bool
 11  Size (KB)          5000 non-null   int64
 12  Created At         5000 non-null   object
 13  Updated At         5000 non-null   object
 14  Pushed At          5000 non-null   object
 15  Default Branch     5000 non-null   object
 16  Owner Login        5000 non-null   object
 17  Owner Type         5000 non-null   object
 18  License            5000 non-null   object
 19  Topics             5000 non-null   object
dtypes: bool(3), int64(4), object(13)
memory usage: 678.8+ KB

In [34]:
cols = [
    "Repository Name",
    "Description",
    "Topics",
    "Domain",
    "Primary Language",
    "Stars Count",
    "Forks Count",
    "Updated At",
]

df = df[cols].copy()

In [27]:
df.shape

(5000, 10)

In [28]:
df.duplicated().sum()

np.int64(3)

In [29]:
df.drop_duplicates(inplace=True)

In [30]:
df.isna().sum()

Repository Name      0
Description          0
Topics               0
Domain               0
Primary Language     0
Stars Count          0
Forks Count          0
Open Issues Count    0
Updated At           0
License              0
dtype: int64

In [36]:
df.sample(1)

,Repository Name,Description,Topics,Domain,Primary Language,Stars Count,Forks Count,Updated At
3826,cs249r_book,Machine Learning Systems,"artificial-intelligence, cloud-ml, computer-sy...",Artificial Intelligence,JavaScript,23535,2823,2026-04-10T10:04:42Z

In [35]:
print(df.columns)

Index(['Repository Name', 'Description', 'Topics', 'Domain',
       'Primary Language', 'Stars Count', 'Forks Count', 'Updated At'],
      dtype='object')

In [37]:
text_cols = [
    'Repository Name',
    'Description', 
    'Topics', 
    'Domain',
    'Primary Language'
    ]