In [3]:
import pandas as pd 
import numpy as np

In [5]:
df= pd.read_csv("../data/raw/github_top_repositories_V2.csv")

In [6]:
df.head(2)

,Domain,Repository Name,Full Name,Description,Primary Language,Stars Count,Forks Count,Open Issues Count,Has Wiki,Has Pages,Has Projects,Size (KB),Created At,Updated At,Pushed At,Default Branch,Owner Login,Owner Type,License,Topics
0,Machine Learning,tensorflow,tensorflow/tensorflow,An Open Source Machine Learning Framework for ...,C++,194622,75263,4302,False,False,True,1302841,2015-11-07T01:19:20Z,2026-04-10T10:08:00Z,2026-04-10T10:13:20Z,master,tensorflow,Organization,Apache License 2.0,"deep-learning, deep-neural-networks, distribut..."
1,Machine Learning,transformers,huggingface/transformers,🤗 Transformers: the model-definition framework...,Python,159148,32816,2365,True,False,True,463713,2018-10-29T13:56:00Z,2026-04-10T10:08:23Z,2026-04-10T10:08:12Z,main,huggingface,Organization,Apache License 2.0,"audio, deep-learning, deepseek, gemma, glm, ha..."

In [8]:
df['Full Name'].value_counts().head(20)

Full Name
explosion/spaCy                                                                               6
ashishpatel26/500-AI-Machine-learning-Deep-learning-Computer-vision-NLP-Projects-with-code    6
AMAI-GmbH/AI-Expert-Roadmap                                                                   5
kornia/kornia                                                                                 5
huggingface/datasets                                                                          5
voxel51/fiftyone                                                                              5
Tencent/ncnn                                                                                  5
Developer-Y/cs-video-courses                                                                  5
microsoft/AI-For-Beginners                                                                    5
tangyudi/Ai-Learn                                                                             5
bharathgs/Awesome-pytorch-list                                                                5
google-ai-edge/mediapipe                                                                      5
roboflow/supervision                                                                          4
visenger/awesome-mlops                                                                        4
recommenders-team/recommenders                                                                4
CMU-Perceptual-Computing-Lab/openpose                                                         4
carla-simulator/carla                                                                         4
libgdx/libgdx                                                                                 4
huggingface/transformers                                                                      4
Lightning-AI/pytorch-lightning                                                                4
Name: count, dtype: int64

In [9]:
df[df['Full Name'] == 'explosion/spaCy' ]

,Domain,Repository Name,Full Name,Description,Primary Language,Stars Count,Forks Count,Open Issues Count,Has Wiki,Has Pages,Has Projects,Size (KB),Created At,Updated At,Pushed At,Default Branch,Owner Login,Owner Type,License,Topics
43,Machine Learning,spaCy,explosion/spaCy,💫 Industrial-strength Natural Language Process...,Python,33432,4669,197,False,False,False,203709,2014-07-03T15:15:40Z,2026-04-10T02:32:54Z,2026-03-28T20:59:29Z,master,explosion,Organization,MIT License,"ai, artificial-intelligence, cython, data-scie..."
234,Deep Learning,spaCy,explosion/spaCy,💫 Industrial-strength Natural Language Process...,Python,33432,4669,197,False,False,False,203709,2014-07-03T15:15:40Z,2026-04-10T02:32:54Z,2026-03-28T20:59:29Z,master,explosion,Organization,MIT License,"ai, artificial-intelligence, cython, data-scie..."
578,Python,spaCy,explosion/spaCy,💫 Industrial-strength Natural Language Process...,Python,33432,4669,197,False,False,False,203709,2014-07-03T15:15:40Z,2026-04-10T02:32:54Z,2026-03-28T20:59:29Z,master,explosion,Organization,MIT License,"ai, artificial-intelligence, cython, data-scie..."
1612,Data Science,spaCy,explosion/spaCy,💫 Industrial-strength Natural Language Process...,Python,33432,4669,197,False,False,False,203709,2014-07-03T15:15:40Z,2026-04-10T02:32:54Z,2026-03-28T20:59:29Z,master,explosion,Organization,MIT License,"ai, artificial-intelligence, cython, data-scie..."
3812,Artificial Intelligence,spaCy,explosion/spaCy,💫 Industrial-strength Natural Language Process...,Python,33432,4669,197,False,False,False,203709,2014-07-03T15:15:40Z,2026-04-10T02:32:54Z,2026-03-28T20:59:29Z,master,explosion,Organization,MIT License,"ai, artificial-intelligence, cython, data-scie..."
4008,Natural Language Processing,spaCy,explosion/spaCy,💫 Industrial-strength Natural Language Process...,Python,33432,4669,197,False,False,False,203709,2014-07-03T15:15:40Z,2026-04-10T02:32:54Z,2026-03-28T20:59:29Z,master,explosion,Organization,MIT License,"ai, artificial-intelligence, cython, data-scie..."

**EDA**

In [30]:
df.shape

(4997, 9)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Domain             5000 non-null   object
 1   Repository Name    5000 non-null   object
 2   Full Name          5000 non-null   object
 3   Description        5000 non-null   object
 4   Primary Language   5000 non-null   object
 5   Stars Count        5000 non-null   int64
 6   Forks Count        5000 non-null   int64
 7   Open Issues Count  5000 non-null   int64
 8   Has Wiki           5000 non-null   bool
 9   Has Pages          5000 non-null   bool
 10  Has Projects       5000 non-null   bool
 11  Size (KB)          5000 non-null   int64
 12  Created At         5000 non-null   object
 13  Updated At         5000 non-null   object
 14  Pushed At          5000 non-null   object
 15  Default Branch     5000 non-null   object
 16  Owner Login        5000 non-null   object
 17  Owner Type         5000 non-null   object
 18  License            5000 non-null   object
 19  Topics             5000 non-null   object
dtypes: bool(3), int64(4), object(13)
memory usage: 678.8+ KB

In [31]:
# Missing Values

df.isna().sum()

Repository Name     0
Description         0
Topics              0
Domain              0
Primary Language    0
Stars Count         0
Forks Count         0
Updated At          0
combined_text       0
dtype: int64

In [32]:
# Checking Duplicates

df.duplicated().sum()

np.int64(0)

In [20]:
# Most common languages

df['Primary Language'].value_counts().head(10)

Primary Language
Python              1086
0                    602
C++                  486
JavaScript           459
Go                   436
Java                 370
Rust                 323
TypeScript           278
Jupyter Notebook     224
C                    107
Name: count, dtype: int64

*Python is the most commonly used language*

In [21]:
# Most common domains

df['Domain'].value_counts()

Domain
Machine Learning               200
Cybersecurity                  200
Robotics                       200
Internet of Things             200
Computer Vision                200
Natural Language Processing    200
Artificial Intelligence        200
Cloud Computing                200
Game Development               200
Backend Development            200
Frontend Development           200
DevOps                         200
Blockchain                     200
Deep Learning                  200
iOS                            200
Android                        200
Web Development                200
Data Science                   200
Rust                           200
Go                             200
C++                            200
Java                           200
Python                         200
Software Engineering           200
JavaScript                     197
Name: count, dtype: int64

*Different domains are balanced in the dataset*

In [37]:
df.loc[33,'Topics']

'angular, archiving, django, dms, document-management, document-management-system, hacktoberfest, machine-learning, ocr, optical-character-recognition, pdf'

In [38]:
# Most frequent topics

df['Topics'].dropna().str.split(",").explode().str.split().value_counts().head(15)

Topics
[machine-learning]           882
[deep-learning]              789
[python]                     728
[javascript]                 441
[android]                    411
[hacktoberfest]              401
[data-science]               397
[computer-vision]            388
[artificial-intelligence]    383
[ai]                         369
[ios]                        314
[nlp]                        313
[pytorch]                    312
[frontend]                   307
[devops]                     290
Name: count, dtype: int64

In [24]:
# Missing Descriptions

(df['Description'].str.strip() == "").sum() # Count of empty entries after removing spaces

np.int64(0)

*No missing descriptions*

In [29]:
# Checking description to determine preprocessing

df['Description'].sample(10)

4847                                           天津大学课程共享计划
1789    High-Performance Symbolic Regression in Python...
1210    The Moby Project - a collaborative project for...
1825    A no-build JavaScript CDN for modern web devel...
4403    High-performance, scalable time-series databas...
3771                               Terraform Maven Plugin
3936                           Data augmentation for NLP
4441    Automatic integrate all Xiaomi devices to Home...
906                        👶🏻 신입 개발자 전공 지식 & 기술 면접 백과사전 📖
820     A powerful 🚀 Android chart view / graph view l...
Name: Description, dtype: object

In [28]:
df.loc[37,'Description']

'吴恩达老师的机器学习课程个人笔记'

**PREPROCESSING**

**removing unnecessary columns**

In [6]:
cols = [
    "Repository Name",
    "Description",
    "Topics",
    "Domain",
    "Primary Language",
    "Stars Count",
    "Forks Count",
    "Updated At",
]

df = df[cols].copy()

In [7]:
df.shape

(5000, 8)

**Handling Duplicates**

In [9]:
df.drop_duplicates(inplace=True)

In [12]:
print(df.columns)

Index(['Repository Name', 'Description', 'Topics', 'Domain',
       'Primary Language', 'Stars Count', 'Forks Count', 'Updated At'],
      dtype='object')

**Feature Engineering**

In [14]:
df['combined_text']= (
    df['Description'] + ' ' +
    df['Topics'] + ' ' +
    df['Domain'] + ' ' +
    df['Primary Language']
)

In [15]:
df.head(1)

,Repository Name,Description,Topics,Domain,Primary Language,Stars Count,Forks Count,Updated At,combined_text
0,tensorflow,An Open Source Machine Learning Framework for ...,"deep-learning, deep-neural-networks, distribut...",Machine Learning,C++,194622,75263,2026-04-10T10:08:00Z,An Open Source Machine Learning Framework for ...

**preprocessing text**

In [16]:
import re
import string

def preprocess(text):
    text= text.lower()
    text= re.sub(r"http\S+\www\S+", "", text)   # urls
    text= text.translate(str.maketrans("","", string.punctuation))  #punctuations
    text= re.sub(r"\s+", " ", text).strip() #extra spaces

    return text

df['combined_text'] = df['combined_text'].apply(preprocess)

In [17]:
df.head(1)

,Repository Name,Description,Topics,Domain,Primary Language,Stars Count,Forks Count,Updated At,combined_text
0,tensorflow,An Open Source Machine Learning Framework for ...,"deep-learning, deep-neural-networks, distribut...",Machine Learning,C++,194622,75263,2026-04-10T10:08:00Z,an open source machine learning framework for ...

In [18]:
df.loc[0,'combined_text']

'an open source machine learning framework for everyone deeplearning deepneuralnetworks distributed machinelearning ml neuralnetwork python tensorflow machine learning c'

In [41]:
df.to_csv("../data/processed/repositories.csv", index = False)