In [1]:
import pandas as pd 
import numpy as np

In [2]:
df= pd.read_csv("../data/github_top_repositories_V2.csv")

In [3]:
df.sample(2)

,Domain,Repository Name,Full Name,Description,Primary Language,Stars Count,Forks Count,Open Issues Count,Has Wiki,Has Pages,Has Projects,Size (KB),Created At,Updated At,Pushed At,Default Branch,Owner Login,Owner Type,License,Topics
3793,Cloud Computing,roboconf-platform,roboconf/roboconf-platform,The core modules and the platform,Java,36,11,77,True,False,True,10972,2014-03-11T16:29:42Z,2024-11-21T11:43:08Z,2023-08-15T17:43:19Z,master,roboconf,Organization,Apache License 2.0,"apache-karaf, automation, cloud, cloud-computi..."
2255,iOS,better-scroll,ustbhuangyi/better-scroll,":scroll: inspired by iscroll, and it supports ...",TypeScript,16499,2591,70,True,True,True,18682,2015-12-18T03:22:16Z,2026-04-10T07:36:14Z,2024-06-14T02:59:46Z,dev,ustbhuangyi,User,MIT License,"better-performance, ios, iscroll, mobile-web, ..."

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Domain             5000 non-null   object
 1   Repository Name    5000 non-null   object
 2   Full Name          5000 non-null   object
 3   Description        5000 non-null   object
 4   Primary Language   5000 non-null   object
 5   Stars Count        5000 non-null   int64
 6   Forks Count        5000 non-null   int64
 7   Open Issues Count  5000 non-null   int64
 8   Has Wiki           5000 non-null   bool
 9   Has Pages          5000 non-null   bool
 10  Has Projects       5000 non-null   bool
 11  Size (KB)          5000 non-null   int64
 12  Created At         5000 non-null   object
 13  Updated At         5000 non-null   object
 14  Pushed At          5000 non-null   object
 15  Default Branch     5000 non-null   object
 16  Owner Login        5000 non-null   object
 17  Owner Type         5000 non-null   object
 18  License            5000 non-null   object
 19  Topics             5000 non-null   object
dtypes: bool(3), int64(4), object(13)
memory usage: 678.8+ KB

In [5]:
cols = [
    "Repository Name",
    "Description",
    "Topics",
    "Domain",
    "Primary Language",
    "Stars Count",
    "Forks Count",
    "Updated At",
]

df = df[cols].copy()

In [6]:
df.shape

(5000, 8)

In [7]:
df.duplicated().sum()

np.int64(3)

In [8]:
df.drop_duplicates(inplace=True)

In [13]:
df.isnull().sum()

Repository Name     0
Description         0
Topics              0
Domain              0
Primary Language    0
Stars Count         0
Forks Count         0
Updated At          0
dtype: int64

In [10]:
df.sample(1)

,Repository Name,Description,Topics,Domain,Primary Language,Stars Count,Forks Count,Updated At
2277,mvt,MVT (Mobile Verification Toolkit) helps with c...,"android, forensics, forensics-tools, ios, mobi...",iOS,Python,12266,1193,2026-04-10T09:59:57Z

In [11]:
print(df.columns)

Index(['Repository Name', 'Description', 'Topics', 'Domain',
       'Primary Language', 'Stars Count', 'Forks Count', 'Updated At'],
      dtype='object')

In [12]:
text_cols = [
    'Repository Name',
    'Description', 
    'Topics', 
    'Domain',
    'Primary Language'
    ]

In [14]:
df['combined_text']= (
    df['Description'] + ' ' +
    df['Topics'] + ' ' +
    df['Domain'] + ' ' +
    df['Primary Language']
)

In [20]:
df.head(1)

,Repository Name,Description,Topics,Domain,Primary Language,Stars Count,Forks Count,Updated At,combined_text
0,tensorflow,An Open Source Machine Learning Framework for ...,"deep-learning, deep-neural-networks, distribut...",Machine Learning,C++,194622,75263,2026-04-10T10:08:00Z,an open source machine learning framework for ...

**preprocessing text**

In [17]:
import re
import string

def preprocess(text):
    text= text.lower()
    text= re.sub(r"http\S+\www\S+", "", text)
    text= text.translate(str.maketrans("","", string.punctuation))
    text= re.sub(r"\s+", " ", text).strip()

    return text

df['combined_text'] = df['combined_text'].apply(preprocess)

In [19]:
df.head(1)

,Repository Name,Description,Topics,Domain,Primary Language,Stars Count,Forks Count,Updated At,combined_text
0,tensorflow,An Open Source Machine Learning Framework for ...,"deep-learning, deep-neural-networks, distribut...",Machine Learning,C++,194622,75263,2026-04-10T10:08:00Z,an open source machine learning framework for ...