In [2]:
import pandas as pd 
import numpy as np

In [3]:
df= pd.read_csv("../data/github_top_repositories_V2.csv")

In [4]:
df.sample(2)

,Domain,Repository Name,Full Name,Description,Primary Language,Stars Count,Forks Count,Open Issues Count,Has Wiki,Has Pages,Has Projects,Size (KB),Created At,Updated At,Pushed At,Default Branch,Owner Login,Owner Type,License,Topics
440,Python,flask,pallets/flask,The Python micro framework for building web ap...,Python,71408,16781,3,False,False,False,11723,2010-04-06T11:11:59Z,2026-04-10T08:59:01Z,2026-04-09T04:04:09Z,main,pallets,Organization,"BSD 3-Clause ""New"" or ""Revised"" License","flask, jinja, pallets, python, web-framework, ..."
4803,Software Engineering,design-patterns-for-humans,kamranahmedse/design-patterns-for-humans,An ultra-simplified explanation to design patt...,0,47681,5502,17,True,False,True,149,2017-02-16T21:24:39Z,2026-04-10T09:23:54Z,2024-12-02T04:54:48Z,master,kamranahmedse,User,0,"architecture, computer-science, design-pattern..."

**EDA**

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Domain             5000 non-null   object
 1   Repository Name    5000 non-null   object
 2   Full Name          5000 non-null   object
 3   Description        5000 non-null   object
 4   Primary Language   5000 non-null   object
 5   Stars Count        5000 non-null   int64
 6   Forks Count        5000 non-null   int64
 7   Open Issues Count  5000 non-null   int64
 8   Has Wiki           5000 non-null   bool
 9   Has Pages          5000 non-null   bool
 10  Has Projects       5000 non-null   bool
 11  Size (KB)          5000 non-null   int64
 12  Created At         5000 non-null   object
 13  Updated At         5000 non-null   object
 14  Pushed At          5000 non-null   object
 15  Default Branch     5000 non-null   object
 16  Owner Login        5000 non-null   object
 17  Owner Type         5000 non-null   object
 18  License            5000 non-null   object
 19  Topics             5000 non-null   object
dtypes: bool(3), int64(4), object(13)
memory usage: 678.8+ KB

In [20]:
# Most common languages

df['Primary Language'].value_counts().head(10)

Primary Language
Python              1086
0                    602
C++                  486
JavaScript           459
Go                   436
Java                 370
Rust                 323
TypeScript           278
Jupyter Notebook     224
C                    107
Name: count, dtype: int64

*Python is the most commonly used language*

In [21]:
# Most common domains

df['Domain'].value_counts()

Domain
Machine Learning               200
Cybersecurity                  200
Robotics                       200
Internet of Things             200
Computer Vision                200
Natural Language Processing    200
Artificial Intelligence        200
Cloud Computing                200
Game Development               200
Backend Development            200
Frontend Development           200
DevOps                         200
Blockchain                     200
Deep Learning                  200
iOS                            200
Android                        200
Web Development                200
Data Science                   200
Rust                           200
Go                             200
C++                            200
Java                           200
Python                         200
Software Engineering           200
JavaScript                     197
Name: count, dtype: int64

*Different domains are balanced in the dataset*

In [ ]:
# Most frequent topics

In [ ]:
# Missing

**PREPROCESSING**

**removing unnecessary columns**

In [6]:
cols = [
    "Repository Name",
    "Description",
    "Topics",
    "Domain",
    "Primary Language",
    "Stars Count",
    "Forks Count",
    "Updated At",
]

df = df[cols].copy()

In [7]:
df.shape

(5000, 8)

In [8]:
df.duplicated().sum()

np.int64(3)

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df.isnull().sum()

Repository Name     0
Description         0
Topics              0
Domain              0
Primary Language    0
Stars Count         0
Forks Count         0
Updated At          0
dtype: int64

In [ ]:
# Checking empty descriptions

(df["Description"].str.strip() == "").sum()

np.int64(0)

In [11]:
df.sample(1)

,Repository Name,Description,Topics,Domain,Primary Language,Stars Count,Forks Count,Updated At
1185,capnproto,Cap'n Proto serialization/RPC system - core to...,0,C++,C++,12971,1042,2026-04-09T17:28:12Z

In [12]:
print(df.columns)

Index(['Repository Name', 'Description', 'Topics', 'Domain',
       'Primary Language', 'Stars Count', 'Forks Count', 'Updated At'],
      dtype='object')

In [14]:
df['combined_text']= (
    df['Description'] + ' ' +
    df['Topics'] + ' ' +
    df['Domain'] + ' ' +
    df['Primary Language']
)

In [15]:
df.head(1)

,Repository Name,Description,Topics,Domain,Primary Language,Stars Count,Forks Count,Updated At,combined_text
0,tensorflow,An Open Source Machine Learning Framework for ...,"deep-learning, deep-neural-networks, distribut...",Machine Learning,C++,194622,75263,2026-04-10T10:08:00Z,An Open Source Machine Learning Framework for ...

**preprocessing text**

In [16]:
import re
import string

def preprocess(text):
    text= text.lower()
    text= re.sub(r"http\S+\www\S+", "", text)   # urls
    text= text.translate(str.maketrans("","", string.punctuation))  #punctuations
    text= re.sub(r"\s+", " ", text).strip() #extra spaces

    return text

df['combined_text'] = df['combined_text'].apply(preprocess)

In [17]:
df.head(1)

,Repository Name,Description,Topics,Domain,Primary Language,Stars Count,Forks Count,Updated At,combined_text
0,tensorflow,An Open Source Machine Learning Framework for ...,"deep-learning, deep-neural-networks, distribut...",Machine Learning,C++,194622,75263,2026-04-10T10:08:00Z,an open source machine learning framework for ...

In [18]:
df.loc[0,'combined_text']

'an open source machine learning framework for everyone deeplearning deepneuralnetworks distributed machinelearning ml neuralnetwork python tensorflow machine learning c'